export const PROVIDER_CHANGED = 'sources.PROVIDER_CHANGED';
export const FETCH_ITEMS_COMPLETE = 'sources.FETCH_ITEMS_COMPLETE';

export const FETCH_STARTED = 'sources.FETCH_STARTED';
export const FETCH_CATEGORIES = 'sources.FETCH_CATEGORIES';
export const FETCH_CATEGORY_ITEMS = 'sources.FETCH_CATEGORY_ITEMS';
export const FETCH_ITEM_DETAILS = 'sources.FETCH_ITEM_DETAILS';
